sonar.projectKey=maestria_front
sonar.projectName=maestria front
sonar.projectVersion=1.0

sonar.sources=src/app/modules/gestion-matricula-academica
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**
sonar.exclusions=**/*.scss

sonar.host.url=http://localhost:9000
sonar.login=sqa_dd6d623002a39f8b41752a12de0fc647e2f847b8
