name: CI Practica Profesional ms-maestriacomputacion-front

on:
  push:
    branches: ['despliegue-de-pruebas-lineamientos']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    permissions:
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Login Dockerhub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/practica-profesional-frontend:latest .
          docker push $DOCKER_USERNAME/practica-profesional-frontend:latest

      - name: Trigger CD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run cd.yml --ref despliegue-de-pruebas-lineamientos
